import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import type { SchemaContributor } from "@better-conversation/core/schema";
import { getPluginExportName, getPluginImportPath } from "./pluginImports.js";

export interface GenerateDrizzleOptions {
  tablePrefix: string;
  contributors: SchemaContributor[];
  outputPath: string;
  provider?: "pg" | "sqlite";
}

function getContributorPluginName(c: SchemaContributor): string | null {
  const p = c as { name?: string };
  return typeof p.name === "string" ? p.name : null;
}

export function generateDrizzle(options: GenerateDrizzleOptions): string {
  const { tablePrefix, contributors, outputPath, provider = "pg" } = options;

  if (provider === "sqlite") {
    return generateSqliteFallback(outputPath, tablePrefix, contributors);
  }

  const lines: string[] = [
    `/** Generated by @better-conversation/cli - run "bc generate" to update */`,
    "",
    `import { buildSchema } from "@better-conversation/core/schema";`,
    `import { translateToDrizzle } from "@better-conversation/adapter-drizzle";`,
  ];

  if (contributors.length > 0) {
    const contributorNames: string[] = [];
    for (const c of contributors) {
      const name = getContributorPluginName(c);
      if (name) {
        const pkg = getPluginImportPath(name);
        const exportName = getPluginExportName(name);
        lines.push(`import { ${exportName} } from "${pkg}";`);
        contributorNames.push(exportName);
      }
    }
    lines.push("");
    lines.push(
      `const merged = buildSchema([${contributorNames.join(", ")}], { tablePrefix: "${tablePrefix}" });`
    );
  } else {
    lines.push("");
    lines.push(`const merged = buildSchema([], { tablePrefix: "${tablePrefix}" });`);
  }

  lines.push(
    `export const bcSchema = translateToDrizzle(merged, { tablePrefix: "${tablePrefix}" });`
  );
  lines.push("");

  const content = lines.join("\n");

  const outDir = dirname(outputPath);
  if (outDir !== ".") {
    try {
      mkdirSync(outDir, { recursive: true });
    } catch {
      // ignore
    }
  }
  writeFileSync(outputPath, content, "utf-8");
  return outputPath;
}

/**
 * For SQLite, we use createSchemaSqlite from adapter-drizzle.
 * Plugin contributions that add tables (e.g. block_history) are not yet supported for SQLite in generate.
 */
function generateSqliteFallback(
  outputPath: string,
  tablePrefix: string,
  _contributors: SchemaContributor[]
): string {
  const content = `/** Generated by @better-conversation/cli - run "bc generate" to update */
/** Note: SQLite schema. Plugin table extensions (e.g. block_history) require PG. */

import { createSchemaSqlite } from "@better-conversation/adapter-drizzle";

export const bcSchema = createSchemaSqlite("${tablePrefix}");
`;

  const outDir = dirname(outputPath);
  if (outDir !== ".") {
    try {
      mkdirSync(outDir, { recursive: true });
    } catch {
      // ignore
    }
  }
  writeFileSync(outputPath, content, "utf-8");
  return outputPath;
}
