import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import type { SchemaContributor } from "@better-conversation/core/schema";

export interface GeneratePrismaOptions {
  tablePrefix: string;
  contributors: SchemaContributor[];
  outputPath: string;
}

/**
 * Generates a Prisma schema block to append to prisma/schema.prisma.
 * User must manually add the generated content.
 */
export function generatePrisma(options: GeneratePrismaOptions): string {
  const { tablePrefix, outputPath } = options;

  const content = `// Generated by @better-conversation/cli - run "bc generate" to update
// Add this block to your prisma/schema.prisma
// Table prefix: ${tablePrefix}

model BcChatter {
  id          String   @id @db.VarChar(36)
  displayName String   @map("display_name") @db.VarChar(255)
  avatarUrl   String?  @map("avatar_url") @db.Text
  entityType  String   @map("entity_type") @db.VarChar(64)
  entityId    String?  @map("entity_id") @db.VarChar(255)
  metadata    Json?    @db.JsonB
  isActive    Boolean  @default(true) @map("is_active")
  createdAt   DateTime @default(now()) @map("created_at")
  updatedAt   DateTime @updatedAt @map("updated_at")

  conversationsConversationCreatedByTobc_conversations BcConversation[] @relation("ConversationCreatedBy")
}

model BcConversation {
  id        String   @id @db.VarChar(36)
  title     String?  @db.VarChar(255)
  status    String   @default("open") @db.VarChar(32)
  entityType String? @map("entity_type") @db.VarChar(64)
  entityId   String? @map("entity_id") @db.VarChar(255)
  createdBy String  @map("created_by") @db.VarChar(36)
  metadata  Json?   @db.JsonB
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @updatedAt @map("updated_at")

  createdByChatter BcChatter @relation("ConversationCreatedBy", fields: [createdBy], references: [id])
}

model BcParticipant {
  id             String    @id @db.VarChar(36)
  conversationId String    @map("conversation_id") @db.VarChar(36)
  chatterId      String    @map("chatter_id") @db.VarChar(36)
  role           String    @db.VarChar(64)
  joinedAt       DateTime  @default(now()) @map("joined_at")
  leftAt         DateTime? @map("left_at")
  metadata       Json?     @db.JsonB
}

model BcBlock {
  id               String   @id @db.VarChar(36)
  conversationId   String   @map("conversation_id") @db.VarChar(36)
  authorId         String   @map("author_id") @db.VarChar(36)
  type             String   @db.VarChar(128)
  body             String?  @db.Text
  metadata         Json?    @db.JsonB
  threadParentId   String?  @map("thread_parent_id") @db.VarChar(36)
  status           String   @default("published") @db.VarChar(32)
  refusalReason    String?  @map("refusal_reason") @db.Text
  flaggedAt        DateTime? @map("flagged_at")
  editedAt         DateTime? @map("edited_at")
  createdAt        DateTime @default(now()) @map("created_at")
}

model BcChatterPermission {
  id        String  @id @db.VarChar(36)
  chatterId String  @map("chatter_id") @db.VarChar(36)
  action    String  @db.VarChar(128)
  scope     String? @db.VarChar(255)
  granted   Boolean @default(true)
}

model BcBlockRegistry {
  type         String   @id @db.VarChar(128)
  schemaJson   Json     @map("schema_json") @db.JsonB
  isBuiltIn    Boolean  @default(false) @map("is_built_in")
  registeredAt DateTime @default(now()) @map("registered_at")
}

model BcRoleRegistry {
  name         String   @id @db.VarChar(64)
  extends      String?  @db.VarChar(64)
  policy       Json     @db.JsonB
  isBuiltIn    Boolean  @default(false) @map("is_built_in")
  registeredAt DateTime @default(now()) @map("registered_at")
}

model BcPolicy {
  id        String   @id @db.VarChar(36)
  level     String   @db.VarChar(32)
  scopeId   String   @map("scope_id") @db.VarChar(255)
  policy    Json     @db.JsonB
  createdAt DateTime @default(now()) @map("created_at")
  updatedAt DateTime @updatedAt @map("updated_at")

  @@unique([level, scopeId])
}
`;

  const outDir = dirname(outputPath);
  if (outDir !== ".") {
    try {
      mkdirSync(outDir, { recursive: true });
    } catch {
      // ignore
    }
  }
  writeFileSync(outputPath, content, "utf-8");
  return outputPath;
}
