/** Generated by @better-conversation/cli - run "bc generate" to update */

import { translateToDrizzle } from "@better-conversation/adapter-drizzle";
import { buildSchema } from "@better-conversation/core/schema";

const merged = buildSchema([], { tablePrefix: "bc_" });
export const bcSchema = translateToDrizzle(merged, { tablePrefix: "bc_" });
